plugins {
    id 'java'
}

if (org.gradle.util.GradleVersion.current() < org.gradle.util.GradleVersion.version('5.0')) {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
} else {
    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

tasks.withType(JavaCompile).all {
    options.encoding = 'UTF-8'
}

tasks.withType(Test).all {
    if (it.hasProperty('failOnNoDiscoveredTests')) {
        failOnNoDiscoveredTests = false
    }
}

task runManifestServerEncodingTest(type: JavaExec) {
    dependsOn testClasses
    classpath = sourceSets.test.runtimeClasspath
    if (org.gradle.util.GradleVersion.current() < org.gradle.util.GradleVersion.version('6.4')) {
        main = 'com.impulse.common.ImpulseManifestServerEncodingTest'
    } else {
        mainClass = 'com.impulse.common.ImpulseManifestServerEncodingTest'
    }
}

check.dependsOn runManifestServerEncodingTest
