buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.54'
    }
}

apply plugin: 'net.minecraftforge.gradle'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

archivesBaseName = 'impulse-forge-1.20.1'

minecraft {
    mappings channel: 'official', version: '1.20.1'
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
    implementation project(':common')
}

tasks.named('jar', Jar).configure {
    from project(':common').sourceSets.main.output
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('processResources', ProcessResources).configure {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') {
        expand 'version': project.version
    }
}
